[package]
name = "tri_avltree"
version = "0.4.3"
edition = "2021"

authors = ["Oden Shirataki <oden.srtk@gmail.com>"]

description = "Customized version of AVLTree library"

repository = "https://github.com/OdenShirataki/tri_avltree"

keywords = ["avltree","database"]
license = "MIT"

[dependencies]

rustc-hash = { version = "1.0", default-features = false }
